albingroen/prismabuilder.io

README.md, components/ImportSchema.tsx, components/Models.tsx, components/Schema.tsx, lib/config.ts
=> feat: Allow for importing a prisma schema

components/WelcomeModal.tsx
you're => your (fix)
friend's => friend has (clarify what is meant)
=> fix(WelcomeModal): wording

pages/_app.tsx
=> feat: Sync data with local storage

components/GraphModal.tsx, components/Modal.tsx, components/Models.tsx, components/SchemaGraph.tsx, components/WelcomeModal.tsx, next.config.js, package.json, pages/_app.tsx, pages/graph.tsx, yarn.lock
- Introduce a Graph view where you can see how your schema flows and is related.
=> feat: Graph View

pages/_app.tsx
- Make sure the graph modal doesn't show up before the welcome modal has been closed.
=> refactor: Only show graph modal after viewing welcome modal

components/Models.tsx, pages/index.tsx, pages/schemas/[schemaId]/models/[id]/index.tsx
- Make delete buttons red
- Add "Get started" list on index page
=> refactor: Introduce small improvements

components/Models.tsx, components/Schema.tsx
- Add "Copy to clipboard" button
- Add "Cancel" button
- Add code background color
=> Schema component improvements

components/ImportSchema.tsx
=> fix: Show error message when importing incomplete schema

components/AddField.tsx, components/UpdateField.tsx, lib/prisma.ts, lib/types.ts, pages/schemas/[schemaId]/models/[id]/index.tsx
- Make the default value selector for fields dynamic depending on which type is chosen
- Some types won't have any default values so then the selector gets hidden (in the future we might introduce a input field so you can type whatever you want then instead of having the choose something from the list).
- Add functionality for removing a default value from a field
=> feat: Improved functionality for default values

pages/schemas/[schemaId]/models/[id]/index.tsx
=> refactor: Show whether a field has the `list` property

components/AddEnum.tsx, components/AddField.tsx, components/Models.tsx, components/UpdateEnum.tsx, components/UpdateField.tsx, lib/context.ts, lib/icons.ts, lib/types.ts, pages/index.tsx, pages/models/[id].tsx, pages/schemas/[schemaId]/models/[id]/index.tsx
Closes #19 
- Introduce the functionality for creating, updating, and using Prisma enums.
=> Enums support

components/AddField.tsx, components/Models.tsx, components/Schemas.tsx, components/UpdateField.tsx
=> refactor: Add links for bug reporting and feature suggesting

components/AddEnum.tsx, components/AddField.tsx, components/ImportSchema.tsx, components/Modal.tsx, components/Models.tsx, components/Schema.tsx, components/Schemas.tsx, components/UpdateEnum.tsx, components/UpdateField.tsx, components/WelcomeModal.tsx, next-env.d.ts, package.json, pages/_document.tsx, pages/schemas/[schemaId]/models/[id]/index.tsx, yarn.lock
Regarding #27
- Add missing `aria-label` and `role` attributes
- Make all buttons from `@prisma/lens` keyboard accessible
- Upgrade Next.js version
=> Improve accessibility

components/AddEnum.tsx, components/Links.tsx, components/Models.tsx, components/Schemas.tsx, components/UpdateEnum.tsx, pages/schemas/[schemaId]/models/[id]/index.tsx
=> refactor: Improve keyboard a11y

components/SchemaGraph.tsx
Closes #31 
- Show enums and their connections in the /graph view.
=> feature: Show enums in graph view

components/AddField.tsx, components/UpdateField.tsx, lib/fields.ts, lib/types.ts, pages/schemas/[schemaId]/models/[id]/index.tsx
Closes #39 
- Add the possibility to append fields with the `@updatedAt` modifier.
=> Add @updatedAt functionality

components/Models.tsx, lib/fields.ts, pages/schemas/[schemaId]/models/[id]/index.tsx
Closes #40 
- Remove the ability to add and use enums if using sqlite
- This doesn't remove already predefined enums or usage of enums though since this could be pretty detrimental
=> Remove ability to add and use enums if using sqlite

package-lock.json, package.json, pages/schemas/[schemaId]/models/[id]/index.tsx
Closes #36 
- Adds functionality for reordering model fields using a drag and drop method
https://user-images.githubusercontent.com/19674362/169685742-fed20a0d-32e2-4022-a78c-2ba2bf7291be.mp4
=> Add drag and drop functionality for reordering fields

components/Models.tsx, lib/fields.ts, lib/prisma.ts, lib/types.ts, package-lock.json, package.json, pages/schemas/[schemaId]/models/[id]/index.tsx
=> 🙌🏾 Added support for sqlserver

components/UpdateEnum.tsx, lib/prisma.ts, lib/types.ts, pages/schemas/[schemaId]/models/[id]/index.tsx
Closes #52 
- Add support for editing the name of enum and the relation not breaking
- Add support for deleting enums
=> Improve enum functionality

components/Models.tsx, lib/fields.ts, pages/schemas/[schemaId]/models/[id]/index.tsx
- Fix relations not showing when using sqlite
This will cause enums to still show if you have enums on a model and switch your database from a provider that supports enums to one that doesn't support them (ie. sqlite). Might be a decent trade off for now though.
=> Fix relations not showing when using sqlite

pages/schemas/[schemaId]/models/[id]/index.tsx
Closes #56 
- Add support for duplicating models and fields
=> Add support for duplicating models and fields

pages/schemas/[schemaId]/models/[id]/index.tsx
- Fix pushing to wrong model after duplication
=> Fix pushing to wrong model after duplication

components/Button.tsx, components/ImportSchema.tsx
- Add support for uploading a schema
=> Add support for uploading a schema

components/Button.tsx, components/Checkbox.tsx, components/Dropdown.tsx, components/Enum.tsx, components/ImportSchema.tsx, components/Modal.tsx, components/Models.tsx, components/PricingModal.tsx, components/Schema.tsx, components/SchemaGraph.tsx, components/Schemas.tsx, components/Sidebar.tsx, components/SidebarItem.tsx, components/Tag.tsx, components/WelcomeModal.tsx, pages/_app.tsx, pages/schemas/[schemaId]/models/[id]/index.tsx, styles/globals.css, tailwind.config.js
- Add dark mode. Theme uses the computers' preferences
=> Add dark mode 🌚

components/Button.tsx, components/Dropdown.tsx, components/Models.tsx, components/Schemas.tsx, components/SidebarItem.tsx, pages/schemas/[schemaId]/models/[id]/index.tsx, styles/globals.css
Closes #59 
- Add support for reordering models
- Change from using model indices as ids to using their names
https://user-images.githubusercontent.com/19674362/221992636-99da6255-726b-4c8b-8551-432047d7d153.mp4
=> Add support for reordering models

components/Models.tsx, components/Schema.tsx, lib/context.ts, lib/utils.ts, pages/_app.tsx, pages/index.tsx, styles/globals.css
Closes #76 
- Add support for sharing of schemas with a link
=> Add support for sharing of schemas with a link
